# PostgreSQL database

development:
  adapter: postgresql
  encoding: unicode
  database: blog_db_development
  pool: 5
  host: localhost
  username: blog_admin
  password: password123

test:
  adapter: postgresql
  encoding: unicode
  database: blog_db_test
  pool: 5
  username: blog_admin
  password: password123

# staging:
#   url: <%= ENV['DATABASE_URL'] %>

# production:
#   url: <%= ENV['DATABASE_URL'] %>
